### ISSUE TITLE
Unable to disable ScalalintImports.disableRelativeImports

### ISSUE THREAD

**Issue by gdeOo** [pdalpra/scalalint#37]
The value of `ScalalintImports.disableRelativeImports` is not checked by the corresponding rule, meaning it cannot be disabled.

---
As a sidenote, this configuration option is mistyped in `docs/src/main/tut/docs/index.md`:
```
Scalalint.disableRelativeImports = true  // should be ScalalintImports, right?
```

**Comment by pdalpra** [comment]
Thx for reporting!

**Comment by pdalpra** [comment]
Scalalint 0.2.1 has been released which include the fix for this issue.
